server:
  port: 9090
spring:
  application:
    name: work-monitor-admin
  profiles:
    active: @profiles.active@

logging:
  config: classpath:logback-plus.xml
  
--- # 监控中心服务端配置
spring:
  boot:
    admin:
      ui:
        title: 工作平台服务监控中心
      context-path: /admin
  security:
    user:
      name: work
      password: 123456

# Actuator 监控端点的配置项
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      external-file: ./logs/${spring.application.name}.log # 和 logback-plus.xml 的 log.path 一致
