# 项目相关配置
ag:
  # 名称
  name: api-generator-platform
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2024

server:
  port: 9000
  servlet:
    # 应用的访问路径
    context-path: /
    
spring:
  application:
    name: ${ag.name} # 项目名
  profiles:
    active: @profiles.active@ # 运行环境
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      
---  # 文件上传
spring.servlet.multipart:
  # 单个文件大小
  max-file-size: 10MB
  # 设置总上传的文件大小
  max-request-size: 20MB

--- # jackson 配置
spring.jackson:
  time-zone: GMT+8
  # 日期格式化
  date-format: yyyy-MM-dd HH:mm:ss
  serialization:
    # 格式化输出
    indent_output: false
    # 忽略无法转换的对象
    fail_on_empty_beans: false
  deserialization:
    # 允许对象忽略 json 中不存在的属性
    fail_on_unknown_properties: false
      
# 日志配置
logging:
  level:
    cn.youngkbt: @logging.level@
    org.springframework: warn
  config: classpath:logback-plus.xml

mybatis-plus:
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  scanPackage: cn.youngkbt.**.mapper

--- # 数据源 DB 初始化加载
spring.datasource:
  select-sql: select * from t_data_source where status = 1 and is_deleted = 0

# security 配置
security:
  enabled: true
  # 排除路径
  excludes:
    # 认证路径
    - /
    - /auth/**
    # 静态资源
    - /**.html
    - /**.css
    - /**.js
    # 公共路径
    - /favicon.ico
    - /error
    # swagger 文档配置
    - /*/api-docs
    - /*/api-docs/**
    # actuator 监控配置
    - /actuator
    - /actuator/**
    - /ai/**
    - /generic-api/**
    - /user/register

# 用户配置
login:
  fail:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# springdoc 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  info:
    title: API 生成器平台
    description: 根据 SQL 生成增删改查的 API
    version: ${ag.version}

--- # Actuator 监控端点的配置项
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      external-file: ./logs/${ag.name}-error.log # Spring Boot Admin 在线查看日志的路径，与 logback-plus.xml 里生成的文件路径一致，这里取得是 error 的日志

# 全局线程池相关配置
thread-pool:
  # 是否开启线程池
  enabled: false
  # 队列最大长度
  queueCapacity: 128
  # 线程池维护线程所允许的空闲时间
  keepAliveSeconds: 300
  
# 数据加密
mybatis-encryptor:
  # 是否开启加密
  enable: true
  # 加密实体类包路径
  class-package: cn.youngkbt.uac.demo
  # 默认加密算法
  algorithm: BASE64
  # 编码方式 BASE64/HEX。默认BASE64
  encode: BASE64
  # 安全秘钥 对称算法的秘钥 如：AES，SM4
  password:
  # 公私钥 非对称算法的公私钥 如：SM2，RSA
  publicKey:
  privateKey:
    
# api 接口加密
api-decrypt:
  # 是否开启全局接口加密
  enabled: true
  # AES 加密头标识
  headerFlag: encrypt-key
  # 响应加密公钥，非对称算法的公私钥，如：SM2，RSA，使用者请自行更换
  # 对应前端解密私钥：MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAKtpzNmnT83pjv2dkeWyCKXvXZ+GLBC0itv3qPBMD9dwQIrcRUQn9YdeQ79M3cPhoaNCd8WMkW+iFQTeTSpz37kM7E4CIbw9ELVUFoYNUGjjJmNbbOBMMeIrjZkNB5gi3Q+UYzqZGzS2x2L8vhKk49JdcEnJFM9LQIiHoPqvLn2XAgMBAAECgYBqK03GQescDt2SGFaVfn/8xxWmCOSiNDENrYflzjbBqbVQTL5aSKW7ApfTlTiGaupCxJiKs1YhXrLGISqKcNrQL7KEDyZeF4tDBCkzLsAciFdEQMHAgexoGNRLO5XI2FUTGPiyDWrRT2qHJSn67Oc25wiYtVqrTvJ3o896krOXgQJBANX/P7KawliWKXUSqYcOJJNqk7fFuknlm/LyZTXzHXf1L0vRx6BxvYDYAKcCJEr9rluJ/ZwzlqV1vbWcaE/QPl0CQQDNDtX+iM9Stenrc1EfUDjBOsXm0Z9Gh775KKXdiBcVrZS3fbPqp9vzqmxtcKd4qXjHrf5J0ZOazq+jDSi1p6SDAkBrsUGIC3PkiuUgIp0n90kW2tqt8Ba425EoqS2gAdIBrWT43gB9UOASOCHT6jMDfjjBnmb/tcKJUACBpc2k5OKNAkA/F0V4HxfK1vW137Eh9UjBCxhAwFZFGRcFCiCeXHTd0p5jJmXo2OSvv8vEkFi2o03qAfqvM7A6fUVE4ZOY8I+JAkBGW8H52YLh2WCnkXoxnqEg1AJZ8/RND5mnkyHxcUcD0+il1q9O2MXPZ5bSs8EXXXWx4gyXLjMd97NvSoDVOEaG
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCraczZp0/N6Y79nZHlsgil712fhiwQtIrb96jwTA/XcECK3EVEJ/WHXkO/TN3D4aGjQnfFjJFvohUE3k0qc9+5DOxOAiG8PRC1VBaGDVBo4yZjW2zgTDHiK42ZDQeYIt0PlGM6mRs0tsdi/L4SpOPSXXBJyRTPS0CIh6D6ry59lwIDAQAB
  # 请求解密私钥，非对称算法的公私钥，如：SM2，RSA，使用者请自行更换
  # 对应前端加密公钥：MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDehF5HmeATamXZ4GmEDxBcNjbrX8n2vYrN52G2wYpmNX6FgdbtVkIEphRT2u+xe9wqfjQFS/qoiLs2juk9XOfDReQ+Bot0bXuFEUknLSFFfaBm2OsAuTPEKolM1SXNCe8kVWYACgSG/+nsfgeQ4PEKZwWOl0xLvXV3NbTKhr6nbwIDAQAB
  privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAN6EXkeZ4BNqZdngaYQPEFw2Nutfyfa9is3nYbbBimY1foWB1u1WQgSmFFPa77F73Cp+NAVL+qiIuzaO6T1c58NF5D4Gi3Rte4URSSctIUV9oGbY6wC5M8QqiUzVJc0J7yRVZgAKBIb/6ex+B5Dg8QpnBY6XTEu9dXc1tMqGvqdvAgMBAAECgYA0ILxZd8HXqpBLt1fguQqzH3xELb+JjyPKUs9AWhzLDvMh4aXxGckDf8i5UEvgv0x3o/MZ3o/NFaMOB/K6Dl64n04eFSZ1SmVxpvL+MEAyZMEndxPzVKoRrCl0uEsLQDFIXWZLYcl3Mdcr7g9EtBBRDnoA7zABJdCDGxZeEGDgOQJBAPzvvU3dEIi5gpg6v/7D41U+t6nBwT0DZrBv/GITMUTwZrxOdZuqHwKDQWKhSuY7usuhLPQ20GR5006ssi/XBI0CQQDhNk9HGpDENs/krYo58myHqna86zaBDRfsu3k0oaojh35f3x5hZlhk8S9yYsaVGE3XzU5CJAhqNpGEdk83/eLrAkBfOGGrzm1LC4t+g5+D6XrLvLCn16lHruAZzA7XXSJPMbF7co4T7BeAeqlC2DW6NwI7ZpHl3jzVlodWNu1d1TSBAkEAiO5Df4D4ekS1XF3jiF4MfOQ5M55z0j1KyaYnCMgusVGFlfcL+r6GikFWzt6dzTMsyURMC8zqzOGG0po4ilu0pwJBAJzQZyPX32Q2Yx9Eb3jlXUD4QLtkrLiNxqycA4kHuLWrQ7MSa6O9wMubslshir1L9y7AwySU0uLZ8jhyitQdyMk=

--- # websocket
websocket:
  # 如果关闭，需要和前端开关一起关闭
  enabled: true
  # 路径
  path: /uac/websocket
  # 设置访问源地址
  allowedOrigins: '*'

default:
  password: 123456