# 项目相关配置
integrate:
  # 名称
  name: integrate-platform
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2024
  
server:
  port: 9040
  servlet:
    # 应用的访问路径
    context-path: /
    
spring:
  application:
    name: ${integrate.name} # 项目名
  profiles:
    active: @profiles.active@ # 运行环境
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  
---  # 文件上传
spring.servlet.multipart:
  # 单个文件大小
  max-file-size: 100MB
  # 设置总上传的文件大小
  max-request-size: 400MB

--- # jackson 配置
spring.jackson:
  time-zone: GMT+8
  # 日期格式化
  date-format: yyyy-MM-dd HH:mm:ss
  serialization:
    # 格式化输出
    indent_output: false
    # 忽略无法转换的对象
    fail_on_empty_beans: false
  deserialization:
    # 允许对象忽略 json 中不存在的属性
    fail_on_unknown_properties: false
    
# 日志配置
logging:
  level:
    cn.youngkbt: @logging.level@
    org.springframework: warn
#  config: classpath:logback-plus.xml
  
mybatis-plus:
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  scanPackage: cn.youngkbt.integrate.system.**.mapper

# springdoc 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  info:
    title: 数据集成平台
    description: 数据集成平台
    version: ${integrate.version}
    
--- # Actuator 监控端点的配置项
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      external-file: ./logs/${integrate.name}-error.log # Spring Boot Admin 在线查看日志的路径，与 logback-plus11.xml 里生成的文件路径一致，这里取得是 error 的日志
      
# 全局线程池相关配置
thread-pool:
  # 是否开启线程池
  enabled: true
  # 队列最大长度
  queueCapacity: 128
  # 线程池维护线程所允许的空闲时间
  keepAliveSeconds: 300

spring:
  cloud:
    openfeign:
      okhttp:
        enabled: true