# 项目相关配置
notice:
  # 名称
  name: notice-platform
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2024
  
server:
  port: 9030
  servlet:
    # 应用的访问路径
    context-path: /
    
spring:
  application:
    name: ${notice.name} # 项目名
  profiles:
    active: @profiles.active@ # 运行环境
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  
---  # 文件上传
spring.servlet.multipart:
  # 单个文件大小
  max-file-size: 10MB
  # 设置总上传的文件大小
  max-request-size: 20MB

--- # jackson 配置
spring.jackson:
  time-zone: GMT+8
  # 日期格式化
  date-format: yyyy-MM-dd HH:mm:ss
  serialization:
    # 格式化输出
    indent_output: false
    # 忽略无法转换的对象
    fail_on_empty_beans: false
  deserialization:
    # 允许对象忽略 json 中不存在的属性
    fail_on_unknown_properties: false
    
# 日志配置
logging:
  level:
    cn.youngkbt: @logging.level@
    org.springframework: warn
  config: classpath:logback-plus.xml
  
mybatis-plus:
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  scanPackage: cn.youngkbt.**.mapper

# springdoc 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  info:
    title: 消息发送平台
    description: 消息发送平台
    version: ${notice.version}
    
--- # Actuator 监控端点的配置项
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      external-file: ./logs/${notice.name}-error.log # Spring Boot Admin 在线查看日志的路径，与 logback-plus.xml 里生成的文件路径一致，这里取得是 error 的日志
      
# 全局线程池相关配置
thread-pool:
  # 是否开启线程池
  enabled: false
  # 队列最大长度
  queueCapacity: 128
  # 线程池维护线程所允许的空闲时间
  keepAliveSeconds: 300
  
--- # 邮件服务
spring:
  mail:
    host: smtp.163.com # 邮件服务器地址
    protocol: smtp # 协议
    username: kele_bingtang@163.com # 发送邮件的邮箱也就是你开通服务的邮箱
    password: GJQDWNWVGYEVTSMB # 开通服务后得到的授权码
    default-encoding: utf-8 # 邮件内容的编码