# 项目相关配置
uac:
  # 名称
  name: uac-platform
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2023

server:
  port: 8090
  servlet:
    # 应用的访问路径
    context-path: /
    
spring:
  application:
    name: ${uac.name} # 项目名
  profiles:
    active: @profiles.active@ # 运行环境
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      
---  # 文件上传
spring.servlet.multipart:
  # 单个文件大小
  max-file-size: 10MB
  # 设置总上传的文件大小
  max-request-size: 20MB

--- # jackson 配置
spring.jackson:
  time-zone: GMT+8
  # 日期格式化
  date-format: yyyy-MM-dd HH:mm:ss
  serialization:
    # 格式化输出
    indent_output: false
    # 忽略无法转换的对象
    fail_on_empty_beans: false
  deserialization:
    # 允许对象忽略 json 中不存在的属性
    fail_on_unknown_properties: false
      
# 日志配置
logging:
  level:
    cn.youngkbt: @logging.level@
    org.springframework: warn
  config: classpath:logback-plus.xml

mybatis-plus:
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  scanPackage: cn.youngkbt.**.mapper

# security 配置
security:
  # 排除路径
  excludes:
    # 认证路径
    - /
    - /auth/**
    - /ids/**
    # 静态资源
    - /**.html
    - /**.css
    - /**.js
    # 公共路径
    - /favicon.ico
    - /error
    # swagger 文档配置
    - /*/api-docs
    - /*/api-docs/**
    # actuator 监控配置
    - /actuator
    - /actuator/**
    - /ai/**

# springdoc 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  info:
    title: UAC 平台
    description: 提供管理后台、用户 App 的所有功能
    version: ${uac.version}

--- # Actuator 监控端点的配置项
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      external-file: ./logs/${uac.name}-error.log # Spring Boot Admin 在线查看日志的路径，与 logback-plus.xml 里生成的文件路径一致，这里取得是 error 的日志

# 用户配置
login:
  fail:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10
    
# 全局线程池相关配置
thread-pool:
  # 是否开启线程池
  enabled: false
  # 队列最大长度
  queueCapacity: 128
  # 线程池维护线程所允许的空闲时间
  keepAliveSeconds: 300
  
# 多租户配置
tenant:
  enable: true
  excludes-table:
    - t_sys_client
    - t_sys_tenant

# 默认配置
default:
  password: 123456 # 新用户的默认密码