--- # 数据源配置
spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/work_uac?useSSL-=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
  username: root
  password: YoungKbt1234
  type: com.alibaba.druid.pool.DruidDataSource
  hikari:
    minimum-idle: 5 # 最小空闲连接数量 
    maximum-pool-size: 10 # 连接池最大连接数，默认是 10 
    max-lifetime: 300000 # 此属性控制池中连接的最长生命周期，值 0 表示无限生命周期，默认 1800000 即 30分钟 
    connection-test-query: SELECT 1

--- # Redis 配置
spring.data:
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10s

--- # 监控中心客户端配置
#spring:
#  cloud:
#    nacos:
#      config: # 配置中心
#        server-addr: 172.16.138.184:8848 # Nacos 地址
#        file-extension: yaml # 文件后缀名
#        namespace: d6824001-7103-4238-a4d5-05bee4a39d2f # 命名空间 ID
#        group: WORK_GROUP # 读取文件所在的组
#  
#        discovery: # 服务注册
#          service: ${spring.application.name} # 使用微服务的名称作为注册的服务名称
#          server-addr: 172.16.138.184:8848 # Nacos服务地址
#          namespace: d6824001-7103-4238-a4d5-05bee4a39d2f # 命名空间 ID
#          group: WORK_GROUP # 读取文件所在的组
#  config: # 指定该项目读取配置中心的文件名
#    import:
#      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
#      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
#      - optional:nacos:nacos-discovery.yaml?group=WORK_GROUP&refreshEnabled=true
#      - nacos:datasource.yaml?group=WORK_GROUP&refreshEnabled=true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: work-uac-platform-abcdefghijklmnopqrstuvwxyz
  expire-time: 43200000 # 12 小时
  refresh-time: 7200000 # token 过期前多少毫秒刷新 token (2小时)

--- # 监控中心配置
spring.boot.admin.client:
  # 增加客户端开关
  enabled: true
  url: http://localhost:9090/admin
  instance:
    name: UAC Platform
    service-host-type: IP
  username: work
  password: 123456
  
--- # Spring Cache
spring:
  cache:
    caffeine:
      expire: 30s # 秒
      capacity: 100
      maximum-size: 1000
    redis:
      time-to-live: 2h
      
--- # Spring ai
#spring:
#  ai:
#    openai:
#      api-key: sk-edEj6eYp4ZBWPZCFE5Bd1a8fAa8d4c918644729f4fDf7f7a
#      base-url: https://api.xty.app